### ISSUE TITLE
Any chance you could save a project compatible with Xcode on Catalina?

### ISSUE THREAD

**Issue by alanruttenberg** [adamd9/Nightscout-MacOS-Menu-Bar#29]
I'm still on Catalina but would love to try the project. It's Xcode 12.4.

**Comment by adamd9** [comment]
Hey @alanruttenberg ! I resaved the project in xcode 12 format, and pushed to develop: https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/tree/develop

Give it a go!

**Comment by alanruttenberg** [comment]
Thanks! I gave it a try, but I think it's not going to fly. I got these errors:
```
Package.resolved file is corrupted or malformed; fix or delete the file to continue
No such module 'LaunchAtLogin
```
That looks fixable maybe, but  I deleted LaunchAtLogin import just to see how much further it would get, and then it dies because (at least) AppStorage is MacOS 11 and up. 

I will *eventually* upgrade from Catalina, at which point I'll give it another try.  Meanwhile I got a minimal BG display in my emacs mode line, where I often am.

**Comment by adamd9** [comment]
Hey @alanruttenberg, just checking, but are you wanting to develop on the project, or just run the app? If you just want to run the app, you can get it in the app store (And it should work on Catalina): https://apps.apple.com/au/app/nightscout-menu-bar/id1639776072?mt=12

**Comment by alanruttenberg** [comment]
Probably not develop other than contributing minor tweaks. I develop but don't do MacOS programming specifically. So priority was getting the app functionality. I hadn't realized that its on the app store. You might want to see about getting added to https://nightscout.github.io/nightscout/downloaders which lists third party apps. Nothing listed under MacOS at the moment.
 
I just went to try to install and it says 12.3 or later is required. Catalina is 10.15.7  :-(

**Comment by adamd9** [comment]
Hey @alanruttenberg I'm not a MacOS developer either, and always appreciative of any contributions so feel free to tinker and submit PRs!

Thanks for the tip on the downloaders - I've submitted a PR on their docs: https://github.com/nightscout/nightscout.github.io/pull/175

**Comment by adamd9** [comment]
Hey @alanruttenberg , so The LaunchAtLogin framework supports as low as 10.13 and I'm sure we could modify the code to support Catalina as well (I think mostly it will be about using the older style of saving settings). 

The main issue I've got is I'm unable to test any changes on Catalina. If you're willing to test, I (or you - I've made you a contributer) can create a new branch and make the changes there. If everything tests good between yours and mine, we'll merge it through and I'll release it.

Let me know if you're keen, and no worries either way!

**Comment by alanruttenberg** [comment]
@adam9 I'm up for it. Sorry for the delay. I've got a deadline coming up for next wednesday but should be able to attend to this once that's done.

**Comment by alanruttenberg** [comment]
Hey @adam9, did you ever get to the LaunchAtLogin mod. Wasn't sure if there was anything I should test yet.

**Comment by adamd9** [comment]
hey @alanruttenberg ! Sorry for the late reply. So I had a go at this and it looks like making it compatible with Catalina would require some pretty significant changes:

- Would need to remove AppStorage and write from scratch a set of methods to **get**, **set**, and take dynamic updates from the userDefaults api that sites behind it. I was able to do **get** **and** set pretty easily, but the settings UI expects more dynamic access to the current values, and this I couldn't easily do.
- Would need to totally rewrite the usage of Scenes to the older type of appDelegate / sceneDelegate

To be honest this is probably to much of a time-sink for me, and doesn't weigh up given it's for an older OS version that less and less people will be using.

[I created a branch](https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/tree/Issue-29---make-compatible-with-catalina) with the work that I've done in case you're feeling game to have a hack at it, but otherwise I'm tapping out on this one sorry!
