### ISSUE TITLE
Can't open settings menu on Sonoma (MacOS 14)

### ISSUE THREAD

**Issue by pyemus** [adamd9/Nightscout-MacOS-Menu-Bar#47]
Just tried it first time here on my Mac with Sonoma and nothing happens when i click "Preferences"...
Could this be the reason?: https://www.reddit.com/r/SwiftUI/comments/16ibgy3/settingslink_on_macos_14_why_it_sucks_and_how_i/

**Comment by mjliedtke** [comment]
I'm having the same issue

**Comment by pyemus** [comment]
Yes, I pulled the project and ran it and the error is: "Please use SettingsLink for opening the Settings scene."
<img width="982" alt="image" src="https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/assets/2339329/fae64034-fca4-4192-8007-57408acf3812">

**Comment by yuvsketch** [comment]
Ive installed it through the appstore, if this info is relevant (with the crashing)

**Comment by adamd9** [comment]
Hey @pyemus @mjliedtke @yuvsketch , thanks for your patience! I'm still trying to get access to a Sonoma device so I can debug and fix this issue. Looks like I'm going to have to rent one (in the cloud) - ha!

In the mean time another user emailed me, because they had discovered that by pressing the keyboard shortcut while the menu is open, you can access preferences! So as a workaround:

1. Open the main menu
2. Pres CMD + ,

Let me know if that works!

**Comment by mjliedtke** [comment]
> Hey @pyemus @mjliedtke @yuvsketch , thanks for your patience! I'm still trying to get access to a Sonoma device so I can debug and fix this issue. Looks like I'm going to have to rent one (in the cloud) - ha!
> 
> In the mean time another user emailed me, because they had discovered that by pressing the keyboard shortcut while the menu is open, you can access preferences! So as a workaround:
> 
> 1. Open the main menu
> 2. Pres CMD + ,
> 
> Let me know if that works!

NP at all!  I can try to compile on mine if that helps?  And no, the shortcut doesn't work for me.

**Comment by adamd9** [comment]
All good @mjliedtke - I've got one in the cloud for a day, taking a look now!

<img width="1274" alt="image" src="https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/assets/4033496/a0b51d24-dacb-40d0-831e-9c9bedaba55c">

**Comment by mjliedtke** [comment]
@adamd9 You rock!  Thank

**Comment by pyemus** [comment]
For me the CMD + , gives same result as clicking the Preferences. Still getting "Please use SettingsLink for opening the Settings scene."

**Comment by adamd9** [comment]
Hey @pyemus @mjliedtke @yuvsketch ! WOW that was an odessy - I couldn't find a straightforward way of implementing the package mentioned in the [reddit article](https://www.reddit.com/r/SwiftUI/comments/16ibgy3/settingslink_on_macos_14_why_it_sucks_and_how_i/), because my implementation uses NSMenuItems rather than a MenuBarExtra. I tried multiple different approaches, and came up against all sorts of weirdness (like buttons not working consistently between MacOS 14 & 13 for example).

In the end, I've come up with a solution that works, but I would consider it a compromise, and eventually I'll just rebuild the whole thing using MenuBarExtra I think (probably when I finally get my own machine updated to Sonoma, so I can do proper testing). 

Anyways - I would really appreciate it if any of you could install this version (download, unzip and copy to your applications folder, then open it by right-clicking while holding the option key the first time) and verify that it works for you guys as expected?

https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/releases/tag/2.5-rc1

**Comment by mjliedtke** [comment]
@adamd9 Works for me...thanks for all the effort!

**Comment by yuvsketch** [comment]
Can I download it from the appstore again? (like an update?)
(Its my work mac, so I can't install from zip)

**Comment by pyemus** [comment]
Awesome it works! :-) thanks for fixing it

**Comment by adamd9** [comment]
Thanks All - I've submitted it to the App Store for review, and I'll update here once it's available for download!

**Comment by adamd9** [comment]
published, no issues reported so closing
